"""add_region_to_vehicle

Revision ID: ed1da7a1798b
Revises: 4f3f697a91eb
Create Date: 2026-02-21 16:03:33.557328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed1da7a1798b'
down_revision: Union[str, Sequence[str], None] = '4f3f697a91eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'region')
    # ### end Alembic commands ###
